const mongoose = require("mongoose");

const offerSchema = mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  createdAt: { type: Date },
  createdBy: { type: String },
  updatedAt: { type: String },
  updatedBy: { type: String },
  projectName: { type: String },
  projectId: { type: String },
  applicantName: { type: String },
  applicantId: { type: String },
  operationSite: { type: String },
  launchDate: { type: String },
  operationalTime: { type: String },
  conditions: { type: String },
  contactPersonName: { type: String },
  contactPersonMobileNumber: { type: String },
  contactPersonEmail: { type: String },
  contactPersonPhoneNumber: { type: String },
  permissionForEquipmentSection: { type: Boolean },
  equipmentSection: { type: String },
  permissionForChargesNotIncludedSection: { type: Boolean },
  chargesNotIncludedSection: { type: String },
  permissionForJourneyAndHolidayCharges: { type: Boolean },
  journeyAndHolidayCharges: { type: String },
  permissionForTerminationAndNoticePeriod: { type: Boolean },
  terminationAndNoticePeriod: { type: String },
  permissionForSubstituteProvisionSection: { type: Boolean },
  substituteProvision: { type: String },
  permissionForCommissionSection: { type: Boolean },
  commissionSection: { type: String },
  permissionForTermsAndConditions: { type: Boolean },
  termsAndConditionsSection: { type: String },
  status: { type: String },
  contactUser: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  deleteStatus:{type: String},
});
offerSchema.index({'$**': 'text'});
module.exports = mongoose.model("Offer", offerSchema);
